service: remak-embed
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  timeout: 600
  memorySize: 1024
  environment:
    NODE_ENV: 'production'
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    DB_URL: ${env:DB_URL}
    S3_BUCKET: ${env:S3_BUCKET}
    OPENSEARCH_NODE: ${env:OPENSEARCH_NODE}
    OPENSEARCH_DOCUMENT_INDEX: ${env:OPENSEARCH_DOCUMENT_INDEX}
    OPENSEARCH_EMBEDDING_INDEX: ${env:OPENSEARCH_EMBEDDING_INDEX}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"
  logRetentionInDays: 14

functions:
  remak-embedding:
    handler: src/handler.handler

constructs:
  remak-embedding-queue:
    type: queue
    worker:
      handler: src/handler.handler
      maxConcurrency: 50
      timeout: 600

plugins:
  - serverless-dotenv-plugin
  - serverless-lift
  - serverless-plugin-typescript
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3
