service: remak-embed
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  remak-embedding:
    handler: src/handler.handler

constructs:
  remak-embedding-queue:
    type: queue
    worker:
      handler: src/handler.handler
      maxConcurrency: 100

plugins:
  - serverless-lift
  - serverless-plugin-typescript
